# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab253a3de527be0760ce25683ddb20c26a37586de19b0d5221ba72361309ed85354f6df90a4927c3bd64324e02762335c029393e0265acc2f97b607e228536e4

test:
  secret_key_base: 66d53b7903e2955e5b45c04cac480ff5107caf8d2a28ef8a7d96a51252d1c0b678d0fb4d8043b730123113531bc4420c5650a0cb4f5963a64027e5a20ceefec6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
